routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::middleware('auth:web')->group(function () {
    Route::resource('projects', 'ProjectsController');
});

app/Milestone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Milestone extends Model
{
    //
}

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Project extends Model
{
    const TODO = 1;
    const WAITING = 2;
    const DONE = 3;

    protected $fillable = ['name', 'owner_id', 'started_at', 'finished_at', 'budget'];

    /* Relationships */
    public function user()
    {
        return $this->belongsTo('App\User', 'owner_id');
        // return $this->belongsTo(User::class, 'owner_id');
    }

    /* Accessors */
    public function getNameAttribute($value)
    {
        return strtolower($value);
    }

    public function getStartedAtAttribute($value)
    {
        // format with Carbon PHP
        $date = new Carbon($value);
        return $date->toFormattedDateString();
    }
    public function getFinishedAtAttribute($value)
    {
        // format with Carbon PHP
        $date = new Carbon($value);
        return $date->toFormattedDateString();
    }

    /* Muttator */
    // WIP
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function projects()
    {
        return $this->hasMany('App\Project', 'owner_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreProject;
use App\Project;
use App\User;
use Gate;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::orderBy('id')->get();

        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        return view('projects.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Request\StoreProject  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProject $request)
    {
        Project::create($request->except('_token'));

        return redirect()->route('projects.index')->with([
            'message' => 'Su proyecto fue creado exitosamente'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $project = Project::findOrFail($id);
            dd($project->toArray());
        } catch (\Exception $e) {
            dd('Error!');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        /*
        Solo a modo de ejemplo.
        Se debería usar
        $project = Project::find($id);
         */

        $project = new Project(); // no necesario con BD
        $project->id = 12; // no necesario con BD
        $project->title = 'Curso Laravel';
        $project->description = 'Descripción del curso.';
        return view('projects.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        /*
        Solo a modo de ejemplo.
        Se debería usar
        $project = Project::find($id);
         */
        $project = new Project(); // esta no corresponde con BD
        $project->title = $request->title;
        $project->description = $request->description;
        // $project->save(); cuando existe conexión a base de datos

        return redirect()->route('projects.index')->with([
            'message' => 'Su proyecto fue editado exitosamente'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $project = Project::findOrFail($id);

            if (Gate::denies('delete-project', $project)) {
                throw new \Exception('Error');
            }

            $project->delete();
            return redirect()->route('projects.index')->with([
                'message' => 'Su proyecto fue eliminado exitosamente'
            ]);
        } catch (\Exception $e) {
            return redirect()->route('projects.index')->with([
                'message' => 'Error al eliminar el proyecto'
            ]);
        }
    }
}

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title', 'Inicio') - Administrador de proyectos</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    @stack('styles')
</head>
<body>

    @auth
        @include('partials.navbar')
    @endauth

    <main class="container">
        @yield('content')
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @stack('scripts')
</body>
</html>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>

          <form method="POST" action="{{ route('logout') }}">
            @csrf
            <button type="submit" class="dropdown-item">Cerrar sesión</button>
          </form>

        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

resources/views/projects/create.blade.php
@extends('layouts.master')

@section('title', 'Crear proyecto')

@section('content')
    <h1>Create Project</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form method="POST" action="{{ route('projects.store') }}">
        @csrf
        <div class="form-group">
            <label for="name">Nombre del proyecto</label>
            <input type="text" value="{{ old('name') }}" class="form-control" id="name" name="name">
        </div>

        <div class="form-group">
            <label for="users">Responsable</label>
            <select class="form-control" id="users" name="owner_id">
                <option value="">Seleccione ...</option>

                @foreach ($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach

            </select>
        </div>

        <div class="form-group">
            <label for="startedAt">Fecha de inicio</label>
            <input type="date" value="{{ old('started_at') }}" class="form-control" id="startedAt" name="started_at">
        </div>

        <div class="form-group">
            <label for="finishedAt">Fecha de término</label>
            <input type="date" value="{{ old('finished_at') }}" class="form-control" id="finishedAt" name="finished_at">
        </div>

        <div class="form-group">
            <label for="budget">Presupuesto</label>
            <input type="text" value="{{ old('budget') }}" class="form-control" id="budget" name="budget">
        </div>

        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
@endsection

@push('scripts')
    <script>
      // Custom JS
    </script>
@endpush

@push('styles')
    <!-- Custom Styles -->
@endpush

resources/views/projects/edit.blade.php
@extends('layouts.master')

@section('title', 'Modificar proyecto')

@section('content')
    <h1>Edit Project</h1>

    <a href="{{ route('projects.index') }}" class="btn btn-info mt-3 mb-3">Volver</a>

    <form method="POST" action="{{ route('projects.update', ['id' => $project->id]) }}">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="title">Título del proyecto</label>
            <input type="text" value="{{ $project->title }}" class="form-control" id="title" name="title">
        </div>
        <div class="form-group">
            <label for="description">Descripción</label>
            <input type="text" value="{{ $project->description }}" class="form-control" id="description" name="description">
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
@endsection

@push('scripts')
    <script>
      // Custom JS
    </script>
@endpush

@push('styles')
    <!-- Custom Styles -->
@endpush

resources/views/projects/index.blade.php
@extends('layouts.master')

@section('title', 'Lista de proyectos')

@section('content')
  <h1>Project index</h1>

  @if (session('message'))
      <div class="alert alert-success">
          {{ session('message') }}
      </div>
  @endif

  <div class="mt-3 mb-3">
    <a href="{{ route('projects.create') }}" class="btn btn-success">Nuevo Proyecto</a>
  </div>

  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Título</th>
          <th scope="col">Encargado</th>
          <th scope="col">Fecha Inicio</th>
          <th scope="col">Fecha Término</th>
          <th scope="col">Presupuesto</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>

        @forelse ($projects as $project)
        <tr>
          <th scope="row">{{ $project->id }}</th>
          <td>{{ $project->name }}</td>
          <td>{{ $project->user->name }}</td>
          <td>{{ $project->started_at }}</td>
          <td>{{ $project->finished_at }}</td>
          <td>$ {{ $project->budget }}</td>
          <td>
              <a href="{{ route('projects.show', $project) }}" class="btn btn-sm btn-outline-info">Ver</a>
              <a href="{{ route('projects.edit', ['id' => $project->id]) }}" class="btn btn-sm btn-outline-warning">Editar</a>

              <form method="POST" action="{{ route('projects.destroy', $project) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-sm btn-outline-danger">Eliminar</button>
              </form>

          </td>
        </tr>
        @empty
          <tr>
            <td>No hay registros</td>
          </tr>
        @endforelse

      </tbody>
    </table>
@endsection

@push('scripts')
    <script>
      // Custom JS
    </script>
@endpush

@push('styles')
    <!-- Custom Styles -->
@endpush